/**
 * Minimal ambient type declarations for the Compact-compiled contract
 * artifacts (bundled by Vite from managed/contract/index.js via the
 * `@managed/contract` alias). The real artifact is generated by
 * `compact compile contracts/creator_authenticity.compact`.
 */

declare module '@managed/contract' {
  export interface ContractLedger {
    readonly verificationId: Uint8Array;
    readonly isAuthentic: boolean;
    readonly minEngagementBps: bigint;
    readonly minConsistency: bigint;
    readonly minAudienceScore: bigint;
    readonly verificationCount: bigint;
  }

  export type WitnessFn = (context: { privateState: unknown }) => [unknown, bigint];

  export interface CompactContractWitnesses {
    followerCount: WitnessFn;
    genuineEngagementCount: WitnessFn;
    postingConsistencyScore: WitnessFn;
    verifiedAudienceScore: WitnessFn;
  }

  export declare class Contract {
    witnesses: CompactContractWitnesses;
    circuits: Record<string, (context: unknown) => unknown>;
    impureCircuits: Record<string, (context: unknown) => unknown>;
    provableCircuits: Record<string, (context: unknown) => unknown>;
    constructor(witnesses: CompactContractWitnesses);
  }

  export declare function ledger(stateOrChargedState: unknown): ContractLedger;
}
